### ISSUE TITLE
Send Sofiya methods writeup, flowchart image and bioscience day poster

### ISSUE THREAD

**Issue by Dremtz** [bos-lab/ANTIVIRAL-TARGETS#17]

**Comment by Andreas-Martinez** [comment]
complete. Methods and flowchart below
[Bioinformatics_Methods_Antiviral_Targets_Version1.docx](https://github.com/bos-lab/ANTIVIRAL-TARGETS/files/13394556/Bioinformatics_Methods_Antiviral_Targets_Version1.docx)
<img width="338" alt="Workflow_Antiviral_Signatures" src="https://github.com/bos-lab/ANTIVIRAL-TARGETS/assets/101658032/d17b174a-161c-461d-b82e-bf6fe617af8b">
